POST http://localhost:9000/api/auth/register
Content-Type: application/json
{
    "username": "bob",
    "password": "1234"
}
###
POST http://localhost:9000/api/auth/login
Content-Type: application/json
{
    "username": "bob",
    "password": "1234"
}
###
GET http://localhost:9000/api/users

###
GET http://localhost:9000/api/auth/logout